#!/usr/bin/env bash
#Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
VarLocation="server_name _;\n\n\tlocation /redirect_me {return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4}"
sudo sed -i "0, /server_name _; /{server_name _;|$VarLocation|} /etc/nginx/sites-available/default"
sudo service nginx restart