#!/usr/bin/env bash
#Install nginx on your web-01 server

sudo apt-get -y update
sudo apt-get upgrade -y
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
varlocation1="server_name _;\n\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4}"
sudo echo "Hello World" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i "0,/server_name _;/{s|server_name _;|$varlocation1|}" /etc/nginx/sites-available/default
sudo service nginx start