#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

sudo apt update && sudo apt upgrade
sudo apt show haproxy
sudo apt install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.5
sudo apt update
sudo apt install haproxy
append_lines="
frontend first_frontend
    bind :80
    default_backend web_servers
    
backend web_servers
    balance roundrobin
    server web-01 23.22.162.227
    server web-02 3.80.117.130"
sudo echo "$append_lines" | sudo tee /etc/haproxy/haproxy.cfg
sudo systemctl restart haproxy