#!/usr/bin/env bash
#check if a file exist and give information about it
school="file"

if [ -e $school ]
then
    echo "school file exists"
else
    echo "school file does not exist"
    if [ -s $school ]
    then 
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi
    if [ -f $school ]
    then
        echo "school is a regular file"
    fi
fi